### ISSUE TITLE
Unknown header field is engine version

### ISSUE THREAD

**Issue by minirop** [mwzzhang/python-YU-RIS-package-file-unpacker#1]
Hello,

in the header, just after the magic number "YPF\0", it's the engine version.
For example `DA 01 00 00` is `474` in decimal so it was compiled with the version `4.7 ver 0.474` (I'm guessing, their version number was *strange*) of the engine.

**Comment by mwzzhang** [comment]
Thanks for letting me know. I will change the field name.
